name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker images
        run: |
          for dir in $(find . -name 'Dockerfile' -exec dirname {} \; | sort -u); do
            LANGUAGE=$(basename $dir)  # Get the directory name as the language name
            IMAGE_NAME="alpine-${LANGUAGE}"  # Create a clear image name
            docker build $dir -t ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}
            docker push ghcr.io/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}
          done
